### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aggsol** [Hapaxia/SfmlSoundSystem#1]
I might use your sound system as a base for my own. Do you mind specifying a license? I'd prefer GPLv3 but I am fine with anything that is compatible to GPLv3.

**Comment by Hapaxia** [comment]
The license is zlib as specified at the top of each code file.
The repository could have a license file too though so I will add that.

**Comment by Hapaxia** [comment]
Added license file in this commit:
https://github.com/Hapaxia/SfmlSoundSystem/commit/2ffd2b414189d888dae689a6a85aa862d2307d38
