### ISSUE TITLE
documentation/usage ?

### ISSUE THREAD

**Issue by a-rabin** [Hapaxia/SfmlSoundSystem#2]
it could be great if you added some documentation/guide for using this system.
thanks.

**Comment by Hapaxia** [comment]
Hi. Thanks for taking the time to have a look at SFML Sound System.

This was created a while ago for a project I was involved with and then generalised to work with any project. That said, it was a while ago and I had almost forgotten about it, to be completely honest.

I have labelled this a "consideration" as I will give this request serious consideration, meaning it is likely that it will happen at some point.

Thank you again.

**Comment by Hapaxia** [comment]
I have now added some documentation to explain the basic usage of the SFML Sound System.

Please visit [the wiki](https://github.com/Hapaxia/SfmlSoundSystem/wiki) to see more information about it :)
